fix: prefer 'bun update --no-save' to 'bun install'

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -206,7 +206,13 @@ jobs:
         name: Configure docker to use gcloud
         run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet
       - name: Install dependencies
-        run: ${{ steps.env-info.outputs.runner }} install || true # To ignore postinstall errors
+        run: |
+          if [[ "${{ steps.env-info.outputs.runner }}" == "bun" ]]; then
+            # Because bun sometimes fails to install private repos (but, update is okay)
+            bun update --no-save
+          else
+            ${{ steps.env-info.outputs.runner }} install || true # To ignore postinstall errors
+          fi
 
       - if: ${{ env.HAS_GCP_SA_KEY_JSON_FOR_FIREBASE == 'true' }}
         name: Create credential file for Firebase
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -95,7 +95,13 @@ jobs:
             ${{ runner.os }}-yarn-v1-
 
       - name: Install dependencies
-        run: ${{ steps.env-info.outputs.runner }} install || true # To ignore postinstall errors
+        run: |
+          if [[ "${{ steps.env-info.outputs.runner }}" == "bun" ]]; then
+            # Because bun sometimes fails to install private repos (but, update is okay)
+            bun update --no-save
+          else
+            ${{ steps.env-info.outputs.runner }} install || true # To ignore postinstall errors
+          fi
       - if: ${{ !inputs.skip_build }}
         name: Build
         run: if [[ "$(cat package.json)" == *'"build":'* ]]; then ${{ steps.env-info.outputs.runner }} run build; fi
